### ISSUE TITLE
Crash with long paths in printlogf0() from l_addwatch()

### ISSUE THREAD

**Issue by martin-langhoff** [axkibe/lsyncd#328]
See the stack trace below. My reading is that l_addwatch() calls printlogf0() the concatenated strings are too long.

```
[root@rl02-v0048 ccpp-2015-07-23-09:32:51-7884]# gdb --core=coredump /usr/bin/lsyncd
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-56.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/lsyncd...Reading symbols from /usr/lib/debug/usr/bin/lsyncd.debug...done.
done.
[New Thread 7884]
Missing separate debuginfo for 
Try: yum --disablerepo='*' --enablerepo='*-debug*' install /usr/lib/debug/.build-id/56/24a39b823ee4f5cf6441832f667d90d0846dff
Reading symbols from /usr/lib64/liblua-5.1.so...Reading symbols from /usr/lib/debug/usr/lib64/liblua-5.1.so.debug...done.
done.
Loaded symbols for /usr/lib64/liblua-5.1.so
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Core was generated by `lsyncd -log all /usr/local/etc/lsyncd_moodledata.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007ff8462d157f in __strlen_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64
(gdb) bt
#0  0x00007ff8462d157f in __strlen_sse42 () from /lib64/libc.so.6
#1  0x00007ff8469ca0a5 in pushstr (L=0x7ff847b32010, str=0x7ff800000002 <Address 0x7ff800000002 out of bounds>) at lobject.c:105
#2  0x00007ff8469ca23b in luaO_pushvfstring (L=0x7ff847b32010, fmt=0x7ff846e11895 " : %s", argp=0x7fff5a6ea010) at lobject.c:123
#3  0x00007ff846e0d869 in printlogf0 (L=0x7ff847b32010, priority=99, cat=0x7ff846e11568 "Inotify", fmt=<value optimized out>) at lsyncd.c:421
#4  0x00007ff846e10901 in l_addwatch (L=0x7ff847b32010) at inotify.c:144
#5  0x00007ff8469c65a1 in luaD_precall (L=0x7ff847b32010, func=0x7ff84cc07730, nresults=1) at ldo.c:319
#6  0x00007ff8469d1229 in luaV_execute (L=<value optimized out>, nexeccalls=<value optimized out>) at lvm.c:587
#7  0x00007ff8469c6a6d in luaD_call (L=0x7ff847b32010, func=0x7ff84cc075e0, nResults=<value optimized out>) at ldo.c:377
#8  0x00007ff8469c6107 in luaD_rawrunprotected (L=0x7fff5a6ea108, f=0x7ff8469c1d20 <f_call>, ud=0x7fff5a6ea400) at ldo.c:116
#9  0x00007ff8469c6182 in luaD_pcall (L=0x7ff847b32010, func=<value optimized out>, u=<value optimized out>, old_top=32, ef=<value optimized out>) at ldo.c:463
#10 0x00007ff8469c1b61 in lua_pcall (L=0x7ff847b32010, nargs=7, nresults=0, errfunc=<value optimized out>) at lapi.c:821
#11 0x00007ff846e10147 in handle_event (L=0x7ff847b32010, event=0x7ff847b7d5b0) at inotify.c:378
#12 0x00007ff846e10539 in inotify_ready (L=0x7ff847b32010, obs=<value optimized out>) at inotify.c:471
#13 0x00007ff846e0f69f in masterloop (argc=<value optimized out>, argv=0x56862ad9) at lsyncd.c:2216
#14 main1 (argc=<value optimized out>, argv=0x56862ad9) at lsyncd.c:2763
#15 0x00007ff846e0fc1a in main (argc=4, argv=0x7fff5a6ea898) at lsyncd.c:2816
(gdb) bt full
#0  0x00007ff8462d157f in __strlen_sse42 () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ff8469ca0a5 in pushstr (L=0x7ff847b32010, str=0x7ff800000002 <Address 0x7ff800000002 out of bounds>) at lobject.c:105
        i_o = 0x7ff84cc077e0
#2  0x00007ff8469ca23b in luaO_pushvfstring (L=0x7ff847b32010, fmt=0x7ff846e11895 " : %s", argp=0x7fff5a6ea010) at lobject.c:123
        s = <value optimized out>
        e = 0x7ff846e11898 "%s"
        n = 7
#3  0x00007ff846e0d869 in printlogf0 (L=0x7ff847b32010, priority=99, cat=0x7ff846e11568 "Inotify", fmt=<value optimized out>) at lsyncd.c:421
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fff5a6ea108, reg_save_area = 0x7fff5a6ea030}}
#4  0x00007ff846e10901 in l_addwatch (L=0x7ff847b32010) at inotify.c:144
        p = 99
        path = 0x7ff84dfc6908 "/mnt/data/moodledata_prod/temp/backup/info_from_mbz_1437657979_pHB1/"
        imode = <value optimized out>
        mask = <value optimized out>
        wd = -1
#5  0x00007ff8469c65a1 in luaD_precall (L=0x7ff847b32010, func=0x7ff84cc07730, nresults=1) at ldo.c:319
        ci = <value optimized out>
        n = 2
        cl = 0x7ff847b3a6e0
        funcr = <value optimized out>
#6  0x00007ff8469d1229 in luaV_execute (L=<value optimized out>, nexeccalls=<value optimized out>) at lvm.c:587
        b = <value optimized out>
        nresults = 1
        i = 1184744463
        ra = 0x7ff84cc07730
        base = <value optimized out>
        k = 0x7ff847b51da0
---Type <return> to continue, or q <return> to quit---
        pc = 0x7ff847b51ce4
#7  0x00007ff8469c6a6d in luaD_call (L=0x7ff847b32010, func=0x7ff84cc075e0, nResults=<value optimized out>) at ldo.c:377
No locals.
#8  0x00007ff8469c6107 in luaD_rawrunprotected (L=0x7fff5a6ea108, f=0x7ff8469c1d20 <f_call>, ud=0x7fff5a6ea400) at ldo.c:116
        lj = {previous = 0x0, b = {{__jmpbuf = {140704331538448, -1966300939656682194, 1, 0, 32, 140704344261984, 1966102076123456814, 1965476602122151214}, 
              __mask_was_saved = 0, __saved_mask = {__val = {0, 210453397508, 532575944795, 472446402679, 140734710588224, 140704331538632, 54, 140704308452992, 
                  140704331538448, 140704331538448, 140704317773356, 140704305219249, 140704331538632, 54, 0, 140704313285884}}}}, status = 0}
#9  0x00007ff8469c6182 in luaD_pcall (L=0x7ff847b32010, func=<value optimized out>, u=<value optimized out>, old_top=32, ef=<value optimized out>) at ldo.c:463
        status = <value optimized out>
        oldnCcalls = 0
        old_allowhooks = 1 '\001'
        old_errfunc = 0
#10 0x00007ff8469c1b61 in lua_pcall (L=0x7ff847b32010, nargs=7, nresults=0, errfunc=<value optimized out>) at lapi.c:821
        c = {func = 0x7ff84cc075e0, nresults = 0}
        status = <value optimized out>
        func = <value optimized out>
#11 0x00007ff846e10147 in handle_event (L=0x7ff847b32010, event=0x7ff847b7d5b0) at inotify.c:378
        event_type = 0x7ff846e1166c "Create"
        after_buf = <value optimized out>
#12 0x00007ff846e10539 in inotify_ready (L=0x7ff847b32010, obs=<value optimized out>) at inotify.c:471
        event = 0x7ff847b7d5b0
        i = <value optimized out>
        len = 2048
        err = <value optimized out>
#13 0x00007ff846e0f69f in masterloop (argc=<value optimized out>, argv=0x56862ad9) at lsyncd.c:2216
        obs = <value optimized out>
        wfds = {fds_bits = {0 <repeats 16 times>}}
        pr = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        rfds = {fds_bits = {8, 0 <repeats 15 times>}}
        sigset = {__val = {0 <repeats 16 times>}}
        pi = <value optimized out>
        tv = {tv_sec = 36, tv_nsec = 390000000}
        have_alarm = <value optimized out>
        force_alarm = <value optimized out>
        now = <value optimized out>
        alarm_time = <value optimized out>
#14 main1 (argc=<value optimized out>, argv=0x56862ad9) at lsyncd.c:2763
        L = 0x7ff847b32010
        lsyncd_runner_file = <value optimized out>
        argp = <value optimized out>
#15 0x00007ff846e0fc1a in main (argc=4, argv=0x7fff5a6ea898) at lsyncd.c:2816
No locals.
(gdb) 
```

**Comment by natefaerber** [comment]
@martin-langhoff , I know it's been a year but wondering if you have tried compiling against Lua 5.2 or 5.3.  It looks like they handle string length in 5.2 and beyond.

**Comment by martin-langhoff** [comment]
No idea. No longer at job where I was using lsyncd with deep/long file paths.

**Comment by axkibe** [comment]
Ja, sounds like a Lua issue to me.

I explicitly use the Lua string library for this, since I didn't want to introduce size limits, and I am not aware that Lua has a documented limit to that.

I'm not aware of any Lsyncd limit to path size (unless its not linked against glibc and its larger than PATH_MAX)
